-- liquibase formatted sql
-- changeset tsliwinski:1

CREATE TABLE RESULT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    FILENAME VARCHAR(32)
);

CREATE TABLE JOB (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CHARSET VARCHAR(128) NOT NULL,
    MIN INT NOT NULL,
    MAX INT NOT NULL,
    QUANTITY INT NOT NULL,
    RESULT_ID BIGINT,
    FOREIGN KEY (RESULT_ID) REFERENCES RESULT(ID)
);


